[tool.poetry]
name = "lingualflowserver"
version = "0.1.0"
description = "Main server of LingualFlow project"
authors = ["Pechenin Vadim <vadim.pechenin2015@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
fastapi = "0.115.14"
sqlalchemy = "1.4.17"
psycopg2 = "2.9.11"
pydantic = "2.11.7"
passlib = "1.7.4"
pytest = "8.4.1"
httpx = "0.28.1"
python-jose = "3.5.0"
pandas = "2.2.3"
spacy = "3.8.11"
sentence-transformers = "5.2.0"
uvicorn = "0.42.0"
scikit-learn = "1.5.2"
numpy = "1.26.0"
python-dotenv = "^1.2.2"
dotenv = "^0.9.9"


[tool.poetry.group.dev.dependencies]
pytest-cov = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
